id: P004533
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:30:28.229120
source_metadata:
  id: bdr:W29678
  title: སུམ་རྟགས་འགྲེལ་པ་ནོར་བུའི་མེ་ལོང
  author: ''
  volumes:
    ac5b651057cc4abbafac10b200885d8a:
      image_group_id: I5565
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
