id: ID7E79E07
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:07:20+00:00'
last_modified: '2022-06-08T01:45:18.766470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29678
  title: སུམ་རྟགས་འགྲེལ་པ་ནོར་བུའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F2C:
      image_group_id: I5565
      title: ''
      total_pages: 130
      order: 1
      base_file: 5F2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
