id: ID7E79E07
legacy_id: P004533
ocr_import_info:
  bdrc_scan_id: W29678
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T14:06:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:16:48.620652+00:00'
last_modified: 2022-09-02 22:17:13.410923
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29678
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29678
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སུམ་རྟགས་འགྲེལ་པ་ནོར་བུའི་མེ་ལོང་།
  author: རྫོགས་ཆེན་མཁན་པོ་ཐུབ་བསྟན་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9463481132535195
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I5565:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5565
      total_pages: 130
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5565.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9463481132535195
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
